# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ff247ee69a3867578a06ad51c4a956bf4dce67c574f4f25248c6adf99e75361fd42d9eb6d0db791e4c0b1d76128ffeb67154708894a7b29c0cacf24b6c7aa2b

test:
  secret_key_base: 12972cbd193b4a0ad56ad2b1fa392dbc130bbee11d76c8268e78a1d6c6599df58156bcbdba83ae1c57ac8b369bf0cb4d05f47a4c3102f5658ce505cb5acbdebc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
